#ifndef SRC_UTILS_FLAGS_H
#define SRC_UTILS_FLAGS_H

#define TIMER_MAX_FREQUENCY	(100)
#define CPU_CORE_AFFINITY	(0)
#define TCP_SENDER_SEND_BUFFER	(1024*1024*2)
#define TCP_SENDER_RECV_BUFFER	(512*1024)


#endif